import * as fs from "fs";
import * as path from "path";

// buck2 auto-reads `.buckconfig.local` (alongside `.buckconfig`) and it takes
// precedence — so we inject the RE config there rather than mutating the
// tracked `.buckconfig`. `execution_platforms` MUST live in a real config file:
// passing it via `--config` is parser-scoped and does NOT reach action
// execution (verified empirically), so the consumer's `buck build` would
// silently keep using the local-only default platform.
export function writeBuckconfigLocal(
  workspace: string,
  grpcAddr: string,
  executionPlatform: string,
): string {
  const body = [
    "# Generated by gilescope/rebuck — RE action cache wiring. Safe to delete.",
    "[build]",
    `execution_platforms = ${executionPlatform}`,
    "",
    "[buck2_re_client]",
    `action_cache_address = ${grpcAddr}`,
    `cas_address = ${grpcAddr}`,
    // engine_address is created unconditionally by the OSS re_grpc client even
    // in cache-only mode; bazel-remote serves Capabilities on the same port.
    `engine_address = ${grpcAddr}`,
    "tls = false",
    // Skip GetCapabilities — without this the client errors "Capabilities
    // client: No address" against a cache-only server.
    "capabilities = false",
    "",
  ].join("\n");
  const dest = path.join(workspace, ".buckconfig.local");
  fs.writeFileSync(dest, body);
  return dest;
}
